project:
  type: website
  output-dir: docs

website:
  title: "Nipun Batra"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: values.qmd
        text: Values
      - href: expectations.qmd
        text: Expectations
      - href: writing-papers.qmd
        text: Writing Papers
      - href: technical-background.qmd
        text: Technical Background
      - href: meetings.qmd
        text: Meetings
      - href: lor.qmd
        text: Letters of Recommendation
      - href: server.qmd
        text: Server Policy
      

format:
  html:
    theme:
      light: [litera, styles.scss]
      dark: [darkly, styles-dark.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap


execute:
  freeze: auto

